export enum AccountComponentEnum{
  TOTAL_FIXED_ASSETS = "TOTAL_DE_ACTIVO_FIJO",
  TOTAL_UNITS_PASIVES ="TOTAL_UNIDADES_PASIVOS",
  ACCOUNTS_RECEIVABLE_ANALYSIS = "ANALISIS_CUENTAS_COBRAR",
  GROSS_PROFIT_ANALYSIS = "ANALISIS_UTILIDAD_BRUTA",
  PAGE_2_3 = "PAGINA_2_3",
  POSITIONS = "POSICIONES",
  OTHER_INCOME = "OTROS INGRESOS",
  INCOME_DEDUCTIONS = "DEDUCCIONES A LOS INGRESOS"
}
